In [6]:
import numpy as np

def get_rref(arr):

    def swap_rows(arr, row1, row2):
        arr[[row1, row2]] = arr[[row2, row1]]

    def scale_row(arr, row, scalar):
        new_row = arr[row] *scalar
        arr[row] = new_row.astype(float)

    def add_row(arr, source_row, target_row, scalar=1):
        arr[target_row] += scalar * arr[source_row]

    def find_pivot_row(arr, col):
        num_rows = arr.shape[0]
        for row in range(col, num_rows):
            if arr[row, col] != 0:
                return row
        return None

    def eliminate_below(arr, pivot_row, pivot_col):
        num_rows, num_cols = arr.shape
        pivot_val = arr[pivot_row, pivot_col]
        for row in range(pivot_row + 1, num_rows):
            factor = arr[row, pivot_col] / pivot_val
            arr[row, pivot_col] = 0
            for col in range(pivot_col + 1, num_cols):
                arr[row, col] -= factor * arr[pivot_row, col]

    def eliminate_above(arr, pivot_row, pivot_col):
        for row in range(pivot_row - 1, -1, -1):
            factor = arr[row, pivot_col]
            arr[row, pivot_col] = 0
            for col in range(pivot_col + 1, arr.shape[1]):
                arr[row, col] -= factor * arr[pivot_row, col]

    def reduce_to_rref(arr):
        num_rows, num_cols = arr.shape
        pivot_col = 0
        for row in range(num_rows):
            if pivot_col >= num_cols:
                break
            pivot_row = find_pivot_row(arr, pivot_col)
            if pivot_row is None:
                pivot_col += 1
                continue
            swap_rows(arr, row, pivot_row)
            scale_row(arr, row, 1 / arr[row, pivot_col])
            eliminate_below(arr, row, pivot_col)
            eliminate_above(arr, row, pivot_col)
            pivot_col += 1
            check_all_zero(arr)

    def check_all_zero(arr):
        zero_rows = np.where(~arr.any(axis=1))[0]
        if zero_rows.size > 0:
            last_row = arr.shape[0] - 1
            for row in zero_rows:
                if row != last_row:
                    swap_rows(arr, row, last_row)
                    last_row -= 1
                    
    reduce_to_rref(arr)
    arr = arr.astype(float)
    return arr

In [7]:
np.random.seed(42)
arr1 = np.random.randint(0, 20, (5, 5)).astype(float)
arr2 = np.random.randint(0, 20, (3, 3)).astype(float)
arr3 = np.random.randint(0, 20, (6, 4)).astype(float)
arr4 = np.random.randint(0, 20, (3, 5)).astype(float)
arr5 = np.random.randint(0, 20, (2, 2)).astype(float)
arr6 = np.random.randint(0, 100, (5, 5)).astype(float)
arr7 = np.random.uniform(0, 40, size=(5, 5)).astype(float)
arr8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float64)
test_cases = [arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8]

In [8]:

"""for index,matrix in enumerate(test_cases):

    print(f"test matrix : {index+1}")
    print("Original Matrix :")
    print(matrix)
    print("Reduced row echolon form : ")
    print(get_rref(matrix))
    print("-------------------------------------------------------------------------------------------------")"""

'for index,matrix in enumerate(test_cases):\n\n    print(f"test matrix : {index+1}")\n    print("Original Matrix :")\n    print(matrix)\n    print("Reduced row echolon form : ")\n    print(get_rref(matrix))\n    print("-------------------------------------------------------------------------------------------------")'

In [9]:
import numpy as np

def has_answers(row_echelon_form):
    num_rows = row_echelon_form.shape[0]
    num_cols = row_echelon_form.shape[1]

    unique_solution = False
    infinite_solutions = True

    if num_rows > num_cols - 1:
        last_row = row_echelon_form[num_rows - 1, :]
        if np.any(last_row[:-1]):
            infinite_solutions = True
            unique_solution = False

    if unique_solution:
        print("The matrix has a unique solution.")
    elif infinite_solutions:
        print("The matrix has infinitely many solutions.")
    else:
        print("The matrix has no solutions.")


In [10]:
np.random.seed(42)
def make_answer_matrix(arr):
    rows = (arr.shape[0])
    array = np.random.randint(0, 100, (rows,1)).astype(float)
    sysyem = np.concatenate((arr, array), axis = 1)
    return sysyem
systems = []
for case in test_cases:
    systems.append(make_answer_matrix(case))
(systems)

[array([[ 6., 19., 14., 10.,  7., 51.],
        [ 6., 18., 10., 10.,  3., 92.],
        [ 7.,  2.,  1., 11.,  5., 14.],
        [ 1.,  0., 11., 11., 16., 71.],
        [ 9., 15., 14., 14., 18., 60.]]),
 array([[11., 19.,  2., 20.],
        [ 4., 18.,  6., 82.],
        [ 8.,  6., 17., 86.]]),
 array([[ 3., 13., 17.,  8., 74.],
        [ 1., 19., 14.,  6., 74.],
        [11.,  7., 14.,  2., 87.],
        [13., 16.,  3., 17., 99.],
        [ 7.,  3.,  1.,  5., 23.],
        [ 9.,  3., 17., 11.,  2.]]),
 array([[ 1.,  9.,  3., 13., 15., 21.],
        [14.,  7., 13.,  7., 15., 52.],
        [12., 17., 14., 12.,  8.,  1.]]),
 array([[14., 12., 87.],
        [ 0.,  6., 29.]]),
 array([[ 8., 87.,  0.,  7., 87., 37.],
        [62., 10., 80.,  7., 34.,  1.],
        [34., 32.,  4., 40., 27., 63.],
        [ 6., 72., 71., 11., 33., 59.],
        [32., 47., 22., 61., 87., 20.]]),
 array([[26.63689426, 23.65191151, 10.98887172, 22.44973703, 15.31707499,
         32.        ],
        [38.86848382,

In [11]:
row_echolon_forms = []
for system in systems :
    row_echolon_forms.append(get_rref(system))
row_echolon_forms

[array([[  1.        ,   0.        ,   0.        ,   0.        ,
           0.        , -39.91231904],
        [ -0.        ,   1.        ,   0.        ,   0.        ,
           0.        ,  20.40052809],
        [  0.        ,   0.        ,   1.        ,   0.        ,
           0.        , -27.17859419],
        [  0.        ,   0.        ,   0.        ,   1.        ,
           0.        ,  20.0564964 ],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           1.        ,  11.82846217]]),
 array([[ 1.        ,  0.        ,  0.        , -5.69957447],
        [ 0.        ,  1.        ,  0.        ,  3.67404255],
        [ 0.        ,  0.        ,  1.        ,  6.44425532]]),
 array([[ 1.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.],
        [-0., -0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.],
        [-0., -0., -0., -0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.]]),
 array([[   1.        ,    0.        ,    0.        ,   46.28571429,
          104.

In [12]:
def answer(arr):
    coef = arr[:,:-1]
    answer = arr[:,-1]
    if np.all(coef[-1] == 0):
        if answer[-1] != 0:
            print("The system is incositnate")
            return
        else:
            print("the system is consistant(infinte answers)")
            return
    elif np.count_nonzero(coef[-1]) > 1 :
        print("the system is consistante(infinte answers)")
        return
    if coef[-1, -1] == 1 and answer[-1] != 0:
        print("the system has unique answer")
        return
        
print(answer(row_echolon_forms[0]))

the system has unique answer
None


In [13]:
row_echolon_forms[0]

array([[  1.        ,   0.        ,   0.        ,   0.        ,
          0.        , -39.91231904],
       [ -0.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  20.40052809],
       [  0.        ,   0.        ,   1.        ,   0.        ,
          0.        , -27.17859419],
       [  0.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  20.0564964 ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.        ,  11.82846217]])

In [14]:
for case in row_echolon_forms:
    print(case)
    answer(case)
    print("--------------------------------------------------------------")

[[  1.           0.           0.           0.           0.
  -39.91231904]
 [ -0.           1.           0.           0.           0.
   20.40052809]
 [  0.           0.           1.           0.           0.
  -27.17859419]
 [  0.           0.           0.           1.           0.
   20.0564964 ]
 [  0.           0.           0.           0.           1.
   11.82846217]]
the system has unique answer
--------------------------------------------------------------
[[ 1.          0.          0.         -5.69957447]
 [ 0.          1.          0.          3.67404255]
 [ 0.          0.          1.          6.44425532]]
the system has unique answer
--------------------------------------------------------------
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [-0. -0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [-0. -0. -0. -0.  1.]
 [ 0.  0.  0.  0.  0.]]
the system is consistant(infinte answers)
--------------------------------------------------------------
[[   1.            0.            0.       

[[  1.   0.  -1. -20.]
 [ -0.   1.   2.  34.]
 [  0.   0.   0. -74.]]
